###findById
GET http://localhost:8765/credits/11-0216444-2-1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzY29wZSI6IlJPTEVfQURNSU5JU1RSQVRPUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNjEyNjg1OCwiZXhwIjoxNzA2MjEzMjU4fQ.w3wQGRZRqpy7jqSWkPPvpi_AyU5e-Qm-YFdh-2tpHjA2AecQ7bvMdxR2RKV-fGDz

###findALl
GET http://localhost:8765/credits
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTkyODY3NiwiZXhwIjoxNzA2MDE1MDc2fQ.hszus17uwT-iHQLvWhIax0ZLNx_5CZw_3qPChK35VglyZuqLaTTt8RGSSbFiNjXE

###create
POST http://localhost:8765/credits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTkxODg1NSwiZXhwIjoxNzA2MDA1MjU1fQ.PfDwJuEduHNTY_5D_gvNvuN7mHQ0gszThOnS-OkWnVt_IZv4Jx82ZMUK8CgT_CZh

{
  "customer_id": "1a72a05f-4b8f-43c5-a889-1ebc6d9dc729",
  "contractNumber": "11-0216444-2-0",
  "contractStartDate": "01.01.2023",
  "totalDebt": 8113.99,
  "currentDebt": 361.99,
  "currency": "BYN",
  "repaymentDate": "01.01.2024",
  "rate": 22.8,
  "iban": "AABBCCCDDDDEEEEEEEEEEEEEEEE",
  "possibleRepayment": true,
  "isClosed": false,
  "customer_type" : "LEGAL"
}

###findAllByCustomerId
GET http://localhost:8765/credits/customers/1a72a05f-4b8f-43c5-a889-1ebc6d9dc728
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiVVNFUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTg0Mjg3OSwiZXhwIjoxNzA1OTI5Mjc5fQ.djvw3_f2I253dm3sNaIr8_trcs6OUPpoRqFkH516g6C94_yOj3kbhsYZFi7-7ToK

###deleteById
DELETE http://localhost:8765/credits/11-0216444-2-0
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiU1VQRVJfVVNFUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTk0NTk0MywiZXhwIjoxNzA2MDMyMzQzfQ.M0JXBCqPr4wByWtVKcHNdpdulynfLHUuprM6qXn9VMTj-4ZHOXEeSLG52RFG4qZs

###updateById
PUT http://localhost:8765/credits/11-0216444-2-0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTk0NzE5MiwiZXhwIjoxNzA2MDMzNTkyfQ.wY5dgJiNVjQ0Da3M1CGrGQmk0H4A-P33xOBGWEz4Da4twrfrkAxDPkGw17QDiGCK

{
  "repaymentDate": "16.08.2023",
  "rate": 22.6,
  "possibleRepayment": true,
  "isClosed": true
}

