server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: http://localhost:8082
          predicates:
            - Path=/jwt/**
        - id: customer_service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/deposits/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/credits/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/cards/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/account/**
        - id: rates_service
          uri: http://localhost:8083
          predicates:
            - Path=/rate/**
      discovery:
        locator:
          enabled: true
