server:
  port: 8765
  forward-headers-strategy: framework
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: http://localhost:8082
          predicates:
            - Path=/jwt/**
        - id: customer_service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/deposits/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/credits/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/cards/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/account/**
        - id: rates_service
          uri: http://localhost:8083
          predicates:
            - Path=/rate/**
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
      discovery:
        locator:
          enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /customers/v3/api-docs
        name: Customer Service
      - url: /rate/v3/api-docs
        name: Rate Service
      - url: /products/v3/api-docs
        name: Product Service
