spring:
  application:
    name: rates_service
  datasource:
    url: jdbc:postgresql://localhost:5432/rates
    username: postgres
    password: 1234
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  profiles:
#    active: dev
  liquibase:
    enabled: true
    contexts: dev
spring-doc:
  packagesToScan: ru.clevertec.bank.currency.controller

exception:
  custom-handler:
    enable: true
aop:
  logging:
    enabled: true
rabbit:
  queue:
    rates: rates
server:
  port: 8083