###findById
GET http://localhost:8082/customers/59e0fee2-8d26-4234-b9e1-b5c4576627d6
Accept: application/json

###findAll
GET http://localhost:8082/customers
Accept: application/json

###saveWithAccount
POST http://localhost:8082/customers
Accept: application/json
Content-Type: application/json

{
  "type" : "LEGAL",
  "email": "example@email.com",
  "phoneCode": "37529",
  "phoneNumber": "1112233",
  "fullName": "Иванов Иван Иванович"
}
