###findById
GET http://localhost:8082/customers/16f60fc4-ce0b-4e2d-9106-648a7dc350f9
Accept: application/json

###findAll
GET http://localhost:8082/customers
Accept: application/json

###save
POST http://localhost:8082/customers
Accept: application/json
Content-Type: application/json

{
  "customer_type": "LEGAL",
  "unp": "ABCDEFGHI",
  "email": "example@email.com",
  "phoneCode": "37529",
  "phoneNumber": "1112233",
  "customer_fullname": "Иванов Иван Иванович"
}

###updateById
PUT http://localhost:8082/customers/5c33d931-4236-449b-9947-c8ed71a4436d
Accept: application/json
Content-Type: application/json

{
  "email": "singleton@email.com",
  "phoneCode": "37533",
  "phoneNumber": "2223344"
}

###deleteById
DELETE http://localhost:8082/customers/16f60fc4-ce0b-4e2d-9106-648a7dc350b5
Accept: application/json

###restoreById
PATCH http://localhost:8082/customers/16f60fc4-ce0b-4e2d-9106-648a7dc350f9
Accept: application/json
