spring:
  application:
    name: product_service
  config:
    import: "optional:configserver:${confighost}"
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 40
  profiles:
    active: dev
  liquibase:
    enabled: true
    contexts: dev
spring-doc:
  packagesToScan: ru.clevertec.bank.product.controller
caching:
  repository: accountRepository, cardRepository, creditRepository, depositRepository
#feign:
#  name: auth-server
#  url : http://localhost:8090
exception:
  custom-handler:
    enable: true
aop:
  logging:
    enabled: true
rabbit:
  exchange: bank
  queue:
    account: account
    card: card
    credit: credit
    deposit: deposit
  header:
    key: message_type
    deposit: deposit_info
    credit: credit-details


server:
  port: 8081

client:
  name: "currency"
  url:
    rate: "http://localhost:8083/rate"
---

spring:
  config:
    activate:
      on-profile: dev
#  liquibase:
#    contexts: dev
caching:
  type: lfu
  size: 5

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test
  liquibase:
    contexts: test
caching:
  type: lfu
  size: 5
---

spring:
  config:
    activate:
      on-profile: redis
  cache:
    redis:
      time-to-live: 300s
  data:
    redis:
      host: localhost
      port: 6379
