###findById
GET http://localhost:8081/credits/11-0216444-2-0
Accept: application/json

###findALl
GET http://localhost:8081/credits
Accept: application/json

###create
POST http://localhost:8081/credits
Content-Type: application/json

{
  "customer_id": "1a72a05f-4b8f-43c5-a889-1ebc6d9dc729",
  "contractNumber": "11-0216444-2-0",
  "contractStartDate": "01.01.2023",
  "totalDebt": 8113.99,
  "currentDebt": 361.99,
  "currency": "BYN",
  "repaymentDate": "01.01.2024",
  "rate": 22.8,
  "iban": "AABBCCCDDDDEEEEEEEEEEEEEEEE",
  "possibleRepayment": true,
  "isClosed": false,
  "customer_type" : "LEGAL"
}

###findAllByCustomerId
GET http://localhost:8081/credits/customers/1a72a05f-4b8f-43c5-a889-1ebc6d9dc728
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiVVNFUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTg0Mjg3OSwiZXhwIjoxNzA1OTI5Mjc5fQ.djvw3_f2I253dm3sNaIr8_trcs6OUPpoRqFkH516g6C94_yOj3kbhsYZFi7-7ToK

###deleteById
DELETE http://localhost:8081/credits/11-0216444-2-0

###updateById
PUT http://localhost:8081/credits/11-0216444-2-0
Content-Type: application/json

{
  "repaymentDate": "16.08.2023",
  "rate": 22.6,
  "possibleRepayment": true,
  "isClosed": true
}

