###findByIban
GET http://localhost:8081/deposits/FR7630001007941234567890185
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTgzMjk4NiwiZXhwIjoxNzA1OTE5Mzg2fQ.T6BvB0HbeBtdAiZSbxRlTQARFgeiHod4xAYocNhV3bypBCliQ0y3EQ-IsDyBKuv8

###findAll
GET http://localhost:8081/deposits?page=0&size=2&sort=depInfo.expDate
Accept: application/json

###findAllByFilter
GET http://localhost:8081/deposits/filter?accIban=FR7630001007941234567890185&greaterThan=true&amount=1000&currency=EUR&page=0&size=2&sort=depInfo.expDate
Accept: application/json

###save
POST http://localhost:8081/deposits
Accept: application/json
Content-Type: application/json

{
  "customer_id": "1a72a05f-4b8f-43c5-a889-1ebc6d9dc729",
  "customer_type": "LEGAL",
  "acc_info": {
    "acc_iban": "AABBCCCDDDDEEEEEEEEEEEEEEEEE",
    "curr_amount": 3000.00,
    "curr_amount_currency": "BYN"
  },
  "dep_info": {
    "rate": 14.50,
    "term_val": 24,
    "term_scale": "M",
    "dep_type": "REVOCABLE",
    "auto_renew": true
  }
}

###updateByIban
PUT http://localhost:8081/deposits/FR7630001007941234567890185
Accept: application/json
Content-Type: application/json

{
  "dep_type": "IRREVOCABLE",
  "auto_renew": false
}

###deleteByIban
DELETE http://localhost:8081/deposits/FR7630001007941234567890185
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsInN1YiI6IjFhNzJhMDVmLTRiOGYtNDNjNS1hODg5LTFlYmM2ZDlkYzcyOSIsImlhdCI6MTcwNTgzMjk4NiwiZXhwIjoxNzA1OTE5Mzg2fQ.T6BvB0HbeBtdAiZSbxRlTQARFgeiHod4xAYocNhV3bypBCliQ0y3EQ-IsDyBKuv8
