###findWithAccountById
GET http://localhost:8081/deposits/1
Accept: application/json

###findAllWithAccounts
GET http://localhost:8081/deposits?page=0&size=3
Accept: application/json

###saveByAccountId
POST http://localhost:8081/deposits/accounts/2
Accept: application/json
Content-Type: application/json

{
  "rate": 14.50,
  "termVal": 6,
  "termScale": "M",
  "expDate": "2025-01-01",
  "depType": "IRREVOCABLE",
  "autoRenew": false
}
