confighost: http://localhost:8888
spring:
  config:
    import: "optional:configserver:${confighost}"
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
