confighost: http://localhost:8888
active: dev

spring:
  config:
    import: "optional:configserver:${confighost}"
    #http://localhost:8888"
  application:
    name : rates
  profiles:
    active: ${active}
